name: "journal-migrator-mysql"

services:

  mysql:
    image: docker.io/mysql:8.0
    platform: linux/amd64
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/mysql-setup.sh:/docker-entrypoint-initdb.d/mysql-setup.sh
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASS}
      MYSQL_DATABASE: journal_migrator_test
      MYSQL_ALLOW_EMPTY_PASSWORD: true
