name: "journal-migrator-postgres"

services:

  postgres:
    image: docker.io/postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: journal_migrator_test
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
