package helpers

import (
	"database/sql"
	"journal-migrator/lib"
	"journal-migrator/pkg/storage"
	"strings"
)

type sampleTable struct {
	ID   int
	Data string
}

type TableHelper struct {
	Config *storage.DatabaseConfig
}

func (helper *TableHelper) GetTableDefinition() string {
	switch helper.Config.Dialect {
	case storage.MysqlDialect:
		return "(id BIGINT AUTO_INCREMENT PRIMARY KEY, data TEXT)"
	case storage.PostgresDialect:
		return "(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, data TEXT)"
	}

	return ""
}

func (helper *TableHelper) GetTableColumnNames() []string {
	rowStruct := new(sampleTable)
	rowFields := lib.StructFieldNames(rowStruct)
	rowColumns := lib.Mapper(rowFields, strings.ToLower)

	return rowColumns
}

func (helper *TableHelper) GetTableParseFunc() func(rows *sql.Rows) ([]sampleTable, error) {
	return lib.ParseRows[sampleTable]
}

func (helper *TableHelper) GetTablePrimaryKey() string {
	return "id"
}
